[package]
name = "bauer"
version = "0.3.1"
edition = "2024"
description = "A derive macro for automatically generating the builder pattern"
license = "Apache-2.0"
repository = "https://github.com/funnyboy-roks/bauer"
categories = ["rust-patterns", "development-tools", "data-structures"]
keywords = ["builder", "constructor", "derive-macro", "type-state", "macro"]
rust-version = "1.85"

[features]
unlimited_range = ["bauer-macros/unlimited_range"]

[dependencies]
bauer-macros = { path = "./bauer-macros" }

[dev-dependencies]
trybuild = "1.0.114"
